webserver:
  hosts:
    myhost.bolt.local:
      ansible_host: 172.20.0.41
      ansible_ssh_common_args: -o StrictHostKeyChecking=no
      ansible_user: root
webservers:
  hosts:
    host1.bolt.local:
      ansible_host: 172.20.0.21
      ansible_ssh_common_args: -o StrictHostKeyChecking=no
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_user: root
    host2.bolt.local:
      ansible_host: 172.20.0.22
      ansible_ssh_common_args: -o StrictHostKeyChecking=no
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_user: root
    host3.bolt.local:
      ansible_host: 172.20.0.23
      ansible_ssh_common_args: -o StrictHostKeyChecking=no
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_user: root
